local ICONPATH = "__nullius__/graphics/icons/"
local ENTITYPATH = "__nullius__/graphics/entity/"

data:extend({
  {
    type = "car",
    name = "nullius-car-1",
    icons = data.raw["item-with-entity-data"]["nullius-car-1"].icons,
    flags = {"placeable-neutral", "player-creation", "placeable-off-grid", "not-flammable"},
    minable = {mining_time = 0.4, result = "nullius-car-1"},
    mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg",volume = 0.8},
    corpse = "car-remnants",
    dying_explosion = "car-explosion",
    alert_icon_shift = util.by_pixel(0, -13),
    crash_trigger = data.raw["car"]["car"].crash_trigger,
    damaged_trigger_effect = data.raw["car"]["car"].damaged_trigger_effect,
    collision_box = {{-0.7, -1}, {0.7, 1}},
    selection_box = {{-0.7, -1}, {0.7, 1}},
    immune_to_rock_impacts = true,
    immune_to_tree_impacts = true,
    resistances = {
      { type = "impact", decrease = 100, percent = 90 },
      { type = "poison", decrease = 50, percent = 80 }
    },

    max_health = 500,
    energy_per_hit_point = 2,
    guns = nil,
    turret_rotation_speed = 0.35 / 60,
    weight = 200,
    braking_power = "80kW",
    friction = .0006,
    rotation_speed = 0.01,
    inventory_size = 80,
    effectivity = 0.6,
    consumption = "15kW",

    burner = {
      fuel_category = "vehicle",
      effectivity = 1,
      fuel_inventory_size = 1,
      burnt_inventory_size = 1,
      smoke = data.raw["car"]["car"].smoke
    },
    light = data.raw["car"]["car"].light,
    render_layer = "object",
    turret_animation = data.raw["car"]["car"].turret_animation,
    sound_no_fuel = data.raw["car"]["car"].sound_no_fuel,
    stop_trigger_speed = 0.15,
    stop_trigger = data.raw["car"]["car"].stop_trigger,
    sound_minimum_speed = 0.25,
    sound_scaling_ratio = 0.8,
    vehicle_impact_sound = data.raw["car"]["car"].vehicle_impact_sound,
    working_sound = data.raw["car"]["car"].working_sound,
    open_sound = data.raw["car"]["car"].open_sound,
    close_sound = data.raw["car"]["car"].close_sound,
    track_particle_triggers = data.raw["car"]["car"].track_particle_triggers,
    water_reflection = data.raw["car"]["car"].water_reflection,

    animation = {
      layers = {
        {
          priority = "low",
          width = 201,
          height = 172,
          frame_count = 2,
          scale = 0.5,
          direction_count = 64,
          shift = util.by_pixel(0+2, -11.5+8.5),
          animation_speed = 8,
          max_advance = 0.2,
          tint = {0.65, 0.65, 0.5},
          stripes = data.raw["car"]["car"].animation.layers[1].hr_version.stripes
        },
        data.raw["car"]["car"].animation.layers[2].hr_version,
        data.raw["car"]["car"].animation.layers[3]
      }
    }
  },

  {
    type = "car",
    name = "nullius-car-2",
    icons = data.raw["item-with-entity-data"]["nullius-car-2"].icons,
    flags = {"placeable-neutral", "player-creation", "placeable-off-grid", "not-flammable"},
    minable = {mining_time = 0.6, result = "nullius-car-2"},
    mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg",volume = 0.8},
    corpse = "car-remnants",
    dying_explosion = "car-explosion",
    alert_icon_shift = util.by_pixel(0, -13),
    crash_trigger = data.raw["car"]["car"].crash_trigger,
    damaged_trigger_effect = data.raw["car"]["car"].damaged_trigger_effect,
    collision_box = {{-0.7, -1}, {0.7, 1}},
    selection_box = {{-0.7, -1}, {0.7, 1}},
    immune_to_rock_impacts = true,
    immune_to_tree_impacts = true,
    resistances = {
      { type = "impact", decrease = 100, percent = 90 },
      { type = "poison", decrease = 50, percent = 80 }
    },

    max_health = 600,
    energy_per_hit_point = 2,
    guns = { "nullius-car-gun" },
    turret_rotation_speed = 0.004,
    weight = 250,
    braking_power = "200kW",
    friction = .0005,
    rotation_speed = 0.015,
    inventory_size = 120,
    effectivity = 0.8,
    consumption = "50kW",

    burner = {
      fuel_category = "vehicle",
      effectivity = 1,
      fuel_inventory_size = 1,
      burnt_inventory_size = 1,
      smoke = data.raw["car"]["car"].smoke
    },
    light = data.raw["car"]["car"].light,
    render_layer = "object",
    turret_animation = data.raw["car"]["car"].turret_animation,
    sound_no_fuel = data.raw["car"]["car"].sound_no_fuel,
    stop_trigger_speed = 0.15,
    stop_trigger = data.raw["car"]["car"].stop_trigger,
    sound_minimum_speed = 0.25,
    sound_scaling_ratio = 0.8,
    vehicle_impact_sound = data.raw["car"]["car"].vehicle_impact_sound,
    working_sound = data.raw["car"]["car"].working_sound,
    open_sound = data.raw["car"]["car"].open_sound,
    close_sound = data.raw["car"]["car"].close_sound,
    track_particle_triggers = data.raw["car"]["car"].track_particle_triggers,
    water_reflection = data.raw["car"]["car"].water_reflection,

    animation = {
      layers = {
        {
          priority = "low",
          width = 201,
          height = 172,
          frame_count = 2,
          scale = 0.5,
          direction_count = 64,
          shift = util.by_pixel(0+2, -11.5+8.5),
          animation_speed = 8,
          max_advance = 0.2,
          tint = {0.5, 0.35, 0.35},
          stripes = data.raw["car"]["car"].animation.layers[1].hr_version.stripes
        },
        data.raw["car"]["car"].animation.layers[2].hr_version,
        data.raw["car"]["car"].animation.layers[3]
      }
    }
  },

  {
    type = "car",
    name = "nullius-car-3",
    icons = data.raw["item-with-entity-data"]["nullius-car-3"].icons,
    flags = {"placeable-neutral", "player-creation", "placeable-off-grid", "not-flammable"},
    minable = {mining_time = 0.8, result = "nullius-car-3"},
    mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg",volume = 0.8},
    corpse = "car-remnants",
    dying_explosion = "car-explosion",
    alert_icon_shift = util.by_pixel(0, -13),
    crash_trigger = data.raw["car"]["car"].crash_trigger,
    damaged_trigger_effect = data.raw["car"]["car"].damaged_trigger_effect,
    collision_box = {{-0.7, -1}, {0.7, 1}},
    selection_box = {{-0.7, -1}, {0.7, 1}},
    immune_to_rock_impacts = true,
    immune_to_tree_impacts = true,
    resistances = {
      { type = "impact", decrease = 100, percent = 90 },
      { type = "poison", decrease = 50, percent = 80 }
    },

    max_health = 800,
    energy_per_hit_point = 2,
    guns = { "nullius-car-gun-2", "nullius-car-launcher" },
    turret_rotation_speed = 0.006,
    weight = 300,
    braking_power = "1.5MW",
    friction = .0004,
    rotation_speed = 0.02,
    inventory_size = 160,
    effectivity = 1,
    consumption = "200kW",
    energy_source = {type = "void"},
    light = data.raw["car"]["car"].light,
    render_layer = "object",
    turret_animation = data.raw["car"]["car"].turret_animation,
    sound_no_fuel = data.raw["car"]["car"].sound_no_fuel,
    stop_trigger_speed = 0.15,
    stop_trigger = data.raw["car"]["car"].stop_trigger,
    sound_minimum_speed = 0.25,
    sound_scaling_ratio = 0.8,
    vehicle_impact_sound = data.raw["car"]["car"].vehicle_impact_sound,
    working_sound = data.raw["car"]["car"].working_sound,
    open_sound = data.raw["car"]["car"].open_sound,
    close_sound = data.raw["car"]["car"].close_sound,
    track_particle_triggers = data.raw["car"]["car"].track_particle_triggers,
    water_reflection = data.raw["car"]["car"].water_reflection,

    animation = {
      layers = {
        {
          priority = "low",
          width = 201,
          height = 172,
          frame_count = 2,
          scale = 0.5,
          direction_count = 64,
          shift = util.by_pixel(0+2, -11.5+8.5),
          animation_speed = 8,
          max_advance = 0.2,
          tint = {0.55, 0.55, 0.7},
          stripes = data.raw["car"]["car"].animation.layers[1].hr_version.stripes
        },
        data.raw["car"]["car"].animation.layers[2].hr_version,
        data.raw["car"]["car"].animation.layers[3]
      }
    }
  },

  {
    type = "car",
    name = "nullius-truck-1",
    icons = data.raw["item-with-entity-data"]["nullius-truck-1"].icons,
    flags = {"placeable-neutral", "player-creation", "placeable-off-grid", "not-flammable"},
    minable = {mining_time = 0.8, result = "nullius-truck-1"},
    mined_sound = {filename = "__core__/sound/deconstruct-large.ogg",volume = 0.8},
    corpse = "tank-remnants",
    dying_explosion = "tank-explosion",
    alert_icon_shift = util.by_pixel(0, -13),
    collision_box = {{-0.9, -1.3}, {0.9, 1.3}},
    selection_box = {{-0.9, -1.3}, {0.9, 1.3}},
    damaged_trigger_effect = data.raw["car"]["tank"].damaged_trigger_effect,
    drawing_box = {{-1.8, -1.8}, {1.8, 1.5}},
    immune_to_tree_impacts = true,
    immune_to_rock_impacts = true,
    resistances = {
      { type = "impact", decrease = 200, percent = 95 },
      { type = "poison", decrease = 100, percent = 90 },
      { type = "explosion", decrease = 50, percent = 80 },
      { type = "physical", decrease = 25, percent = 70 },
      { type = "fire", decrease = 25, percent = 70 },
      { type = "laser", decrease = 10, percent = 60 },
      { type = "acid", decrease = 5, percent = 50 }
    },

    max_health = 2500,
    energy_per_hit_point = 0.25,
    guns = { "nullius-truck-gun", "nullius-truck-launcher" },
    turret_rotation_speed = 0.008,
    turret_return_timeout = 300,
    weight = 4000,
    braking_power = "500kW",
    friction = 0.002,
    terrain_friction_modifier = 0.4,
    rotation_speed = 0.0025,
    inventory_size = 200,
    effectivity = 0.8,
    consumption = "500kW",

    burner = {
      fuel_category = "vehicle",
      effectivity = 1,
      fuel_inventory_size = 2,
      burnt_inventory_size = 2,
      smoke = data.raw["car"]["tank"].smoke
    },
    light = data.raw["car"]["tank"].light,
    turret_animation = data.raw["car"]["tank"].turret_animation,
    sound_no_fuel = data.raw["car"]["tank"].sound_no_fuel,
    sound_minimum_speed = 0.2,
    sound_scaling_ratio = 0.8,
    vehicle_impact_sound = data.raw["car"]["tank"].vehicle_impact_sound,
    working_sound = data.raw["car"]["tank"].working_sound,
    stop_trigger_speed = 0.1,
    stop_trigger = data.raw["car"]["tank"].stop_trigger,
    open_sound = data.raw["car"]["tank"].open_sound,
    close_sound = data.raw["car"]["tank"].close_sound,
    tank_driving = true,
    track_particle_triggers = data.raw["car"]["tank"].track_particle_triggers,
    water_reflection = data.raw["car"]["tank"].water_reflection,
    animation = data.raw["car"]["tank"].animation
  },

  {
    type = "car",
    name = "nullius-truck-2",
    icons = data.raw["item-with-entity-data"]["nullius-truck-2"].icons,
    flags = {"placeable-neutral", "player-creation", "placeable-off-grid", "not-flammable"},
    minable = {mining_time = 1, result = "nullius-truck-2"},
    mined_sound = {filename = "__core__/sound/deconstruct-large.ogg",volume = 0.8},
    corpse = "tank-remnants",
    dying_explosion = "tank-explosion",
    alert_icon_shift = util.by_pixel(0, -13),
    collision_box = {{-0.9, -1.3}, {0.9, 1.3}},
    selection_box = {{-0.9, -1.3}, {0.9, 1.3}},
    damaged_trigger_effect = data.raw["car"]["tank"].damaged_trigger_effect,
    drawing_box = {{-1.8, -1.8}, {1.8, 1.5}},
    immune_to_tree_impacts = true,
    immune_to_rock_impacts = true,
    resistances = {
      { type = "impact", decrease = 200, percent = 95 },
      { type = "poison", decrease = 100, percent = 90 },
      { type = "explosion", decrease = 50, percent = 80 },
      { type = "physical", decrease = 25, percent = 70 },
      { type = "fire", decrease = 25, percent = 70 },
      { type = "laser", decrease = 10, percent = 60 },
      { type = "acid", decrease = 5, percent = 50 }
    },

    max_health = 8000,
    energy_per_hit_point = 0.1,
    guns = { "nullius-truck-gun-2", "nullius-truck-launcher" },
    turret_rotation_speed = 0.01,
    turret_return_timeout = 300,
    weight = 5000,
    braking_power = "2MW",
    friction = 0.0015,
    terrain_friction_modifier = 0.3,
    rotation_speed = 0.005,
    inventory_size = 300,
    effectivity = 1,
    consumption = "1MW",

    burner = {
      fuel_categories = {"nullius-nuclear", "vehicle"},
      effectivity = 1,
      fuel_inventory_size = 1,
      burnt_inventory_size = 1,
      smoke = data.raw["car"]["tank"].smoke
    },
    light = data.raw["car"]["tank"].light,
    turret_animation = data.raw["car"]["tank"].turret_animation,
    sound_no_fuel = data.raw["car"]["tank"].sound_no_fuel,
    sound_minimum_speed = 0.2,
    sound_scaling_ratio = 0.8,
    vehicle_impact_sound = data.raw["car"]["tank"].vehicle_impact_sound,
    working_sound = data.raw["car"]["tank"].working_sound,
    stop_trigger_speed = 0.1,
    stop_trigger = data.raw["car"]["tank"].stop_trigger,
    open_sound = data.raw["car"]["tank"].open_sound,
    close_sound = data.raw["car"]["tank"].close_sound,
    tank_driving = true,
    track_particle_triggers = data.raw["car"]["tank"].track_particle_triggers,
    water_reflection = data.raw["car"]["tank"].water_reflection,

    animation = {
      layers = {
        {
          priority = "low",
          width = 270,
          height = 212,
          frame_count = 2,
          direction_count = 64,
          shift = util.by_pixel(0, -16 + 6),
          animation_speed = 8,
          max_advance = 1,
          scale = 0.5,
          tint = {0.45, 0.5, 0.55},
          stripes = data.raw["car"]["tank"].animation.layers[1].hr_version.stripes
        },
        data.raw["car"]["tank"].animation.layers[2].hr_version,
        data.raw["car"]["tank"].animation.layers[3]
      }
    }
  },

  {
    type = "spider-vehicle",
    name = "nullius-mecha",
    localised_name = {"", {"entity-name.nullius-mecha"}, " ", 1},
    icons = data.raw["item-with-entity-data"]["nullius-mecha"].icons,
    minable = {mining_time = 1.5, result = "nullius-mecha"},
    collision_box = {{-1 * 1, -1 * 1}, {1 * 1, 1 * 1}},
    sticker_box = {{-1.5 * 1, -1.5 * 1}, {1.5 * 1, 1.5 * 1}},
    selection_box = {{-1 * 1, -1 * 1}, {1 * 1, 1 * 1}},
    drawing_box = {{-3 * 1, -4 * 1}, {3 * 1, 2 * 1}},
    sound_minimum_speed = 0.1,
    sound_scaling_ratio = 0.6,
    weight = 5000,
    braking_force = 1,
    friction_force = 1,
    flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
    collision_mask = {},
    max_health = 2000,
    resistances = {
      { type = "impact", decrease = 100, percent = 90 },
      { type = "explosion", decrease = 50, percent = 50 },
      { type = "physical", decrease = 25, percent = 70 },
      { type = "fire", decrease = 25, percent = 70 },
      { type = "laser", decrease = 10, percent = 60 },
      { type = "acid", decrease = 5, percent = 50 }
    },
    mined_sound = data.raw["spider-vehicle"]["spidertron"].mined_sound,
    open_sound = data.raw["spider-vehicle"]["spidertron"].open_sound,
    close_sound = data.raw["spider-vehicle"]["spidertron"].close_sound,
    working_sound = data.raw["spider-vehicle"]["spidertron"].working_sound,
    minimap_representation = data.raw["spider-vehicle"]["spidertron"].minimap_representation,
    corpse = "spidertron-remnants",
    dying_explosion = "spidertron-explosion",
    energy_per_hit_point = 1,
    guns = {
      "nullius-mecha-gun", "nullius-mecha-launcher",
      "nullius-mecha-drone-launcher-1", "nullius-mecha-drone-launcher-2"
    },
    inventory_size = 150,
    trash_inventory_size = 20,
    equipment_grid = "nullius-mecha-grid-1",
    height = 1.5,
    torso_rotation_speed = 0.005,
    chunk_exploration_radius = 3,
    selection_priority = 51,
    energy_source = { type = "void" },
    movement_energy_consumption = "500kW",
    automatic_weapon_cycling = false,
    chain_shooting_cooldown_modifier = 1,
    graphics_set = data.raw["spider-vehicle"]["spidertron"].graphics_set,
    spider_engine = data.raw["spider-vehicle"]["spidertron"].spider_engine
  },

  {
    type = "spider-vehicle",
    name = "nullius-mecha-2",
    localised_name = {"", {"entity-name.nullius-mecha"}, " ", 2},
    icons = data.raw["item-with-entity-data"]["nullius-mecha-2"].icons,
    minable = {mining_time = 2, result = "nullius-mecha-2"},
    collision_box = {{-1 * 1, -1 * 1}, {1 * 1, 1 * 1}},
    sticker_box = {{-1.5 * 1, -1.5 * 1}, {1.5 * 1, 1.5 * 1}},
    selection_box = {{-1 * 1, -1 * 1}, {1 * 1, 1 * 1}},
    drawing_box = {{-3 * 1, -4 * 1}, {3 * 1, 2 * 1}},
    sound_minimum_speed = 0.1,
    sound_scaling_ratio = 0.6,
    weight = 5000,
    braking_force = 1,
    friction_force = 1,
    flags = {"placeable-neutral", "player-creation", "placeable-off-grid"},
    collision_mask = {},
    max_health = 3000,
    resistances = {
      { type = "impact", decrease = 200, percent = 90 },
      { type = "explosion", decrease = 100, percent = 50 },
      { type = "physical", decrease = 50, percent = 70 },
      { type = "fire", decrease = 50, percent = 70 },
      { type = "laser", decrease = 20, percent = 60 },
      { type = "acid", decrease = 10, percent = 50 }
    },
    mined_sound = data.raw["spider-vehicle"]["spidertron"].mined_sound,
    open_sound = data.raw["spider-vehicle"]["spidertron"].open_sound,
    close_sound = data.raw["spider-vehicle"]["spidertron"].close_sound,
    working_sound = data.raw["spider-vehicle"]["spidertron"].working_sound,
    minimap_representation = data.raw["spider-vehicle"]["spidertron"].minimap_representation,
    corpse = "spidertron-remnants",
    dying_explosion = "spidertron-explosion",
    energy_per_hit_point = 1,
    guns = {
      "nullius-mecha-gun", "nullius-mecha-launcher",
      "nullius-mecha-drone-launcher-1", "nullius-mecha-drone-launcher-2"
    },
    inventory_size = 250,
    trash_inventory_size = 30,
    equipment_grid = "nullius-mecha-grid-2",
    height = 1.5,
    torso_rotation_speed = 0.005,
    chunk_exploration_radius = 3,
    selection_priority = 51,
    energy_source = { type = "void" },
    movement_energy_consumption = "500kW",
    automatic_weapon_cycling = false,
    chain_shooting_cooldown_modifier = 1,
    graphics_set = data.raw["spider-vehicle"]["spidertron"].graphics_set,
    spider_engine = data.raw["spider-vehicle"]["spidertron"].spider_engine
  },

  {
    type = "rocket-silo",
    name = "nullius-silo",
    icon = "__base__/graphics/icons/rocket-silo.png",
    icon_size = 64,
    icon_mipmaps = 4,
    flags = {"placeable-player", "player-creation"},
    crafting_categories = {"rocketry"},
    rocket_parts_required = 1,
    crafting_speed = 1,
    rocket_result_inventory_size = 12,
    module_specification = {
      module_slots = 4,
      module_info_icon_shift = {0, 3.3}
    },
    fixed_recipe = "nullius-rocket",
    show_recipe_icon = false,
    allowed_effects = {"consumption", "speed", "productivity", "pollution"},
    minable = {mining_time = 8, result = "nullius-silo"},
    max_health = 5000,
    corpse = "rocket-silo-remnants",
    dying_explosion = "rocket-silo-explosion",
    collision_box = {{-4.2, -4.2}, {4.2, 4.2}},
    selection_box = {{-4.5, -4.5}, {4.5, 4.5}},
    hole_clipping_box = { {-2.75, -1.15}, {2.75, 2.25} },
    resistances = {
      { type = "impact", decrease = 100, percent = 90 },
      { type = "fire", decrease = 100, percent = 90 },
      { type = "explosion", decrease = 100, percent = 90 },
      { type = "physical", decrease = 20, percent = 50 }
    },
    damaged_trigger_effect = data.raw["rocket-silo"]["rocket-silo"].damaged_trigger_effect,
    vehicle_impact_sound = data.raw["rocket-silo"]["rocket-silo"].vehicle_impact_sound,
    energy_source = {
      type = "electric",
      usage_priority = "primary-input",
      drain = "200kW"
    },
    energy_usage = "800kW",
    idle_energy_usage = "200KW",
    lamp_energy_usage = "200KW",
    active_energy_usage = "2600KW",
    rocket_entity = "rocket-silo-rocket",
    times_to_blink = 3,
    light_blinking_speed = 1 / (3 * 60),
    door_opening_speed = 1 / (4.25 * 60),

    base_engine_light = data.raw["rocket-silo"]["rocket-silo"].base_engine_light,
    shadow_sprite = data.raw["rocket-silo"]["rocket-silo"].shadow_sprite,
    hole_sprite = data.raw["rocket-silo"]["rocket-silo"].hole_sprite,
    hole_light_sprite = data.raw["rocket-silo"]["rocket-silo"].hole_light_sprite,
    rocket_shadow_overlay_sprite = data.raw["rocket-silo"]["rocket-silo"].rocket_shadow_overlay_sprite,
    rocket_glow_overlay_sprite = data.raw["rocket-silo"]["rocket-silo"].rocket_glow_overlay_sprite,
    door_back_sprite = data.raw["rocket-silo"]["rocket-silo"].door_back_sprite,
    door_front_sprite = data.raw["rocket-silo"]["rocket-silo"].door_front_sprite,
    door_back_open_offset = {1.8, -1.8 * 0.43299225},
    door_front_open_offset = {-1.8, 1.8 * 0.43299225},
    base_day_sprite = data.raw["rocket-silo"]["rocket-silo"].base_day_sprite,
    red_lights_back_sprites = data.raw["rocket-silo"]["rocket-silo"].red_lights_back_sprites,
    red_lights_front_sprites = data.raw["rocket-silo"]["rocket-silo"].red_lights_front_sprites,
    satellite_animation = data.raw["rocket-silo"]["rocket-silo"].satellite_animation,
    arm_01_back_animation = data.raw["rocket-silo"]["rocket-silo"].arm_01_back_animation,
    arm_02_right_animation = data.raw["rocket-silo"]["rocket-silo"].arm_02_right_animation,
    arm_03_front_animation = data.raw["rocket-silo"]["rocket-silo"].arm_03_front_animation,
    base_front_sprite = data.raw["rocket-silo"]["rocket-silo"].base_front_sprite,
    silo_fade_out_start_distance = 8,
    silo_fade_out_end_distance = 15,
    alarm_sound = data.raw["rocket-silo"]["rocket-silo"].alarm_sound,
    clamps_on_sound = data.raw["rocket-silo"]["rocket-silo"].clamps_on_sound,
    clamps_off_sound = data.raw["rocket-silo"]["rocket-silo"].clamps_off_sound,
    doors_sound = data.raw["rocket-silo"]["rocket-silo"].doors_sound,
    raise_rocket_sound = data.raw["rocket-silo"]["rocket-silo"].raise_rocket_sound,
    open_sound = data.raw["rocket-silo"]["rocket-silo"].open_sound,
    close_sound = data.raw["rocket-silo"]["rocket-silo"].close_sound,
    working_sound = data.raw["rocket-silo"]["rocket-silo"].working_sound,
    flying_sound = data.raw["rocket-silo"]["rocket-silo"].flying_sound
  }
})
