require("prototypes.reskin")
require("prototypes.category")
require("prototypes.item.fluid")
require("prototypes.item.intermediate")
require("prototypes.item.buildings")
require("prototypes.item.plumbing")
require("prototypes.item.equipment")
require("prototypes.item.biology")
require("prototypes.item.drone")
require("prototypes.item.weapon")
require("prototypes.item.module")
require("prototypes.item.recipe")
require("prototypes.item.broken")
require("prototypes.item.void")
require("prototypes.item.landfill")
require("prototypes.item.boxing")
require("prototypes.entity.furnace")
require("prototypes.entity.assembler")
require("prototypes.entity.miner")
require("prototypes.entity.plumbing")
require("prototypes.entity.chemistry")
require("prototypes.entity.energy")
require("prototypes.entity.power_pole")
require("prototypes.entity.turbine")
require("prototypes.entity.chest")
require("prototypes.entity.train")
require("prototypes.entity.vehicle")
require("prototypes.entity.robot")
require("prototypes.entity.drone")
require("prototypes.entity.beacon")
require("prototypes.entity.logistics")
require("prototypes.entity.environment")
require("prototypes.entity.equipment")
require("prototypes.entity.landing")
require("prototypes.technology")
require("prototypes.checkpoint")
require("prototypes.upgrades")
require("prototypes.mods")
require("prototypes.inputs")
require("prototypes.achievements")

settings.startup["alien-biomes-disable-vegetation"].value = "Enabled"
settings.startup["bobmods-logistics-inserteroverhaul"].value = true

data.raw["map-settings"]["map-settings"].pollution.enabled = false
data.raw["map-settings"]["map-settings"].difficulty_settings.research_queue_setting = "always"
